### ISSUE TITLE
BSD0 license cites someone's name

### ISSUE THREAD

**Issue by techknowlogick** [spdx/license-list#23]
The BSD0 license cites the name of "Copyright (C) 2006 by Rob Landley rob@landley.net".

Issue copied from: https://github.com/go-gitea/gitea/issues/5397

**Comment by waldyrious** [comment]
@techknowlogick why was this issue closed?

**Comment by techknowlogick** [comment]
@waldyrious closed because per this repo's README this repo is archived, and not the appropriate place to have an issue open. I hadn't read the README before opening this issue.

My understanding is that https://github.com/spdx/license-list-data is the appropriate place

**Comment by goneall** [comment]
@waldyrious @techknowlogick  - the best repo for this issue would be https://github.com/spdx/license-list-XML

The license-list-XML repo is where "source" is maintained for the license list.  The license-list-data repository stores different data representations generated from the license-list-XML repo.

**Comment by techknowlogick** [comment]
@goneall thanks for that tip 😄

**Comment by jhabdas** [comment]
Because 0BSD is a public domain dedication equivalent license I believe the **copyright line should be omitted** entirely from the license text. In fact, that's why [some authors](https://github.com/nazar-pc/PickMeUp/pull/216#issuecomment-463326671), myself included, have begun using it.

Additionally, it [may be](https://github.com/nazar-pc/PickMeUp/pull/216#issuecomment-463253170) good form to add the License title at the top of the file for recognizability while updating the license text.

**Comment by ghost** [comment]
Because 0BSD is a public domain dedication equivalent license I believe the **copyright line should be omitted** entirely from the license text. In fact, that's why [some authors](https://github.com/nazar-pc/PickMeUp/pull/216#issuecomment-463326671), myself included, have begun using it.

Additionally, it [may be](https://github.com/nazar-pc/PickMeUp/pull/216#issuecomment-463253170) good form to add the License title at the top of the file for recognizability while updating the license text.

/cc @landley fyi

**Comment by landley** [comment]
Legally it's still a license, which means it's a permission grant from the copyright holder. The berne convention says the material is still copyrighted whether or not there's a notice, which is why it's hard to place it into the public domain, there's no explicit mechanism for _undoing_ a copyright in any of the legislation. The best we can do is a permission grant that gives people other than the copyright holder(s) the same rights they would have if the work was in the public domain.)

The notice makes it clear _who_ is giving the permission grant, and it also helps corporate legal departments feel comfortable.
